
platform :ios, '7.0'

target ‘RelaxTime’ do
   pod 'AFNetworking','~>2.5.4'
  pod ‘Masonry’
  pod ‘SDWebImage’
  pod ‘MJRefresh’
  pod ‘YYModel’, ‘~>0.9.10’
  pod ‘SVProgressHUD’
  pod 'XRWaterfallLayout'
  pod ‘DACircularProgress’
  pod 'MBProgressHUD'
  pod ‘FMDB’
  pod 'AVOSCloud' 
   pod 'LeanCloudSocial'
end
